update @gelatonetwork/limit-orders-react and its dependencies
QuickSwap/interface-v2 pull request #110
Opened 2022-03-02 09:14 UTC by 3mp8r3

2022-03-04 01:56 UTC, FriskyHamTitz requested changes

2022-03-04 01:56 UTC, FriskyHamTitz commented on package.json
> +    "s": "^1.0.0",
What is this dependency?

2022-03-04 02:38 UTC, 3mp8r3 commented on package.json
> +    "s": "^1.0.0",
Please elt me remove it.

2022-03-07 14:07 UTC, FriskyHamTitz approved these changes

2022-03-07 14:08 UTC, FriskyHamTitz approved these changes

2022-03-07 15:20 UTC, merged