completed: Replace Spritz finance on UI with dragons dispatch
QuickSwap/interface-v2 pull request #1156
Opened 2024-01-09 06:31 UTC by CodeSnooker

2024-01-09 06:31 UTC, CodeSnooker commented
![](https://github.trello.services/images/mini-trello-icon.png) [Replace Spritz finance on UI with dragons dispatch](https://trello.com/c/ey1kKynu/488-replace-spritz-finance-on-ui-with-dragons-dispatch)

2024-01-09 07:06 UTC, sameepsi requested changes

2024-01-09 07:06 UTC, sameepsi commented on src/pages/SwapPage/BuySellWidget/DraginDipatchAdvertisement.tsx
> +import { Box, Button, CircularProgress } from '@material-ui/core';
Please fix the name of this file

2024-01-10 19:08 UTC, CodeSnooker commented on src/pages/SwapPage/BuySellWidget/DraginDipatchAdvertisement.tsx
> +import { Box, Button, CircularProgress } from '@material-ui/core';
done

2024-01-11 07:10 UTC, sameepsi commented on src/pages/SwapPage/BuySellWidget/DragonDipatchAdvertisement.tsx
> +import { Box, Button, CircularProgress } from '@material-ui/core';
fix the name of this file

2024-01-12 08:37 UTC, sameepsi approved these changes

2024-01-12 08:37 UTC, merged