Create page to convert QUICK
QuickSwap/interface-v2 pull request #134
Opened 2022-04-10 16:49 UTC by totop716

https://app.zeplin.io/project/61661650e8d9b1b72191b00d/screen/6237f1693be1da1124cc73ec

2022-04-14 00:17 UTC, FriskyHamTitz requested changes

2022-04-14 00:17 UTC, FriskyHamTitz commented on src/pages/ConvertQUICKPage/ConvertQUICKPage.tsx
> +            {t('conversionRate')}: 1 QUICK = 100 QUICK-v2
Isn't the conversion rate 1 to 1000

2022-04-14 00:17 UTC, FriskyHamTitz commented on src/pages/ConvertQUICKPage/ConvertQUICKPage.tsx
> +                setQUICKV2Amount((Number(value) * 100).toString());
100 should be 1000 and it should be stored in a const which is reused

2022-04-14 00:17 UTC, FriskyHamTitz commented on src/pages/ConvertQUICKPage/ConvertQUICKPage.tsx
> +                    (Number(quickBalance.toExact()) * 100).toString(),
Same comment as above

2022-04-14 00:17 UTC, FriskyHamTitz commented on src/pages/ConvertQUICKPage/ConvertQUICKPage.tsx
> +                setQUICKAmount((Number(value) / 100).toString());
Same comment

2022-04-21 10:42 UTC, sameepsi approved these changes

2022-04-22 13:48 UTC, FriskyHamTitz approved these changes

2022-04-22 13:51 UTC, merged