Separate css styles
QuickSwap/interface-v2 pull request #159
Opened 2022-05-16 03:30 UTC by totop716

2022-05-28 21:30 UTC, FriskyHamTitz requested changes
Please break this into multiple PRs. Create this to be more component based so it can be merged and verified easier

2022-05-30 02:48 UTC, totop716 commented on src/components/PositionCard/PositionCard.tsx
> -  return (
I removed the unused components

2022-05-30 02:51 UTC, totop716 commented on src/components/AddressInput/AddressInput.tsx
> +        error ? 'border-error' : 'border-primaryDark'
It was passing error to the styles hook but I removed the styles hook and added class based on error

2022-05-30 02:52 UTC, totop716 commented on src/components/AddressInput/AddressInput.tsx
> +        className={error ? 'text-error' : 'text-primaryText'}
This is same as above

2022-05-30 03:05 UTC, totop716 commented on src/components/PairsTable/PairsTable.tsx
> +          <p>${oneDayFee}</p>
It was showing `24h Fees` as `NaN` on mobile view and this fixed the issue.

2022-05-30 03:09 UTC, totop716 commented on src/components/StakeQuickModal/StakeQuickModal.tsx
> +                handleChange={(evt: any, value) => {
It returned error after moving CSS of `ColoredSlider` component and updated `onChange` prop to `handleChange` to fix the error.

2022-05-30 03:09 UTC, totop716 commented on src/components/StakeSyrupModal/StakeSyrupModal.tsx
> +                handleChange={(_, value) => {
It returned error after moving CSS of `ColoredSlider` component and updated `onChange` prop to `handleChange` to fix the error.

2022-05-30 03:11 UTC, totop716 commented on src/components/SwapTokenDetails/SwapTokenDetails.tsx
>            href={`https://polygonscan.com/token/${tokenAddress}`}
We are not using testnet for now and I will update this in another PR.

2022-05-30 03:25 UTC, totop716 commented on src/components/ButtonSwitch/ButtonSwitch.tsx
> +                  minHeight: minHeight,
This is to fix `ButtonSwitch` on the `Info` section of swap pro mode

2022-06-01 23:37 UTC, FriskyHamTitz commented on yarn.lock
> +immutable@^4.0.0:
What is this used for why don't I see any add to package.json for this?

2022-06-01 23:39 UTC, FriskyHamTitz commented
Please resolve all the conflicts. After we merge this I'm going to create a new branch for the next version that we can start working on.

2022-06-02 01:31 UTC, merged