Refactoring
QuickSwap/interface-v2 pull request #210
Opened 2022-06-14 20:04 UTC by RitzyDevBox

2022-06-23 01:14 UTC, totop716 requested changes
We still need `tokens.json`?

2022-06-23 01:22 UTC, totop716 commented on src/constants/index.ts
> +    UNI: {
I think this is not necessary and we can remove this value. We are using this value in the hooks for farms/syrups in `stake/hooks.ts` and `useUniContract` in `hooks/useContract.ts` which is not used and can be removed.

2022-06-24 13:11 UTC, sameepsi requested changes

2022-06-24 13:11 UTC, sameepsi commented on src/state/stake/hooks.ts
>  export function useNewLairInfo(): LairInfo {
Lets keep this function but as I said in the previous comments that we can't showcase new lair in the UI as yet

2022-06-24 14:53 UTC, RitzyDevBox commented on src/components/WalletModal/PendingView.tsx
> +  const isCypherD = ethereum?.isCypherD;
New Wallet integration which we discussed I created a seperate PR for them ill remove this

2022-06-27 14:47 UTC, RitzyDevBox commented on src/constants/index.ts
> +        '0x9719d867A500Ef117cC201206B8ab51e794d3F82',
this address was taken from tokens.json see this line: https://github.com/QuickSwap/interface-v2/blob/24503826d7e27ab0e23df45db96936c274e12893/src/constants/tokens.json#L82

2022-06-28 03:35 UTC, sameepsi approved these changes

2022-06-28 09:07 UTC, totop716 approved these changes
Looks good

2022-06-28 15:43 UTC, merged