Move text messages of components to JSON
QuickSwap/interface-v2 pull request #211
Opened 2022-06-15 02:46 UTC by totop716

2022-06-17 10:49 UTC, sameepsi commented on public/locales/en.json
> +  "newToMatic": "New to Matic?",
Change this to "New to Polygon".

2022-06-17 10:51 UTC, sameepsi requested changes
As per the comment

2022-06-23 18:20 UTC, totop716 commented on public/locales/en.json
> +  "newToMatic": "New to Matic?",
Fixed this and pushed a commit

2022-06-29 07:47 UTC, sameepsi approved these changes

2022-06-29 07:47 UTC, merged