Investigate a better way to calculate daily volume
QuickSwap/interface-v2 pull request #83
Opened 2022-02-09 02:59 UTC by 3mp8r3

2022-02-10 18:21 UTC, FriskyHamTitz requested changes

2022-02-10 18:21 UTC, FriskyHamTitz commented on src/utils/index.ts
> +    //   query: ETH_PRICE(),
Remove commented out code.

2022-02-10 18:21 UTC, FriskyHamTitz commented on src/utils/index.ts
> +    // const twoWeekData = twoWeekResult.data.uniswapFactories[0];
Removed commented out code

2022-02-11 04:52 UTC, 3mp8r3 commented on src/utils/index.ts
> +    // const twoWeekData = twoWeekResult.data.uniswapFactories[0];
removed commented code

2022-02-11 04:53 UTC, 3mp8r3 commented on src/utils/index.ts
> +    //   query: ETH_PRICE(),
removed commented code

2022-02-13 20:33 UTC, 3mp8r3 commented on src/state/stake/hooks.ts
> +  const oneDayOldBlock = await getBlockFromTimestamp(utcOneDayBack);
It is using on there. 
![image](https://user-images.githubusercontent.com/3013114/153773751-b3a79a95-0470-4f7b-b45e-902cfddce535.png)

2022-02-14 00:44 UTC, merged